/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Dimension;
import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import model.CredentialDirectory;
import model.Credentials;
import model.Operations;
import model.City;
import javax.swing.JCheckBox;
import model.MainSys;

/**
 *
 * @author harshitaranganath
 */
public class SystemAdmin extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdmin
     */
    Operations crudops1;
    CredentialDirectory cred;
    City city1;
    MainSys mainSystem;

    public SystemAdmin(MainSys mainSystem, CredentialDirectory cred) {
        initComponents();
        this.cred = cred;
        this.crudops1 = crudops1;
        this.mainSystem = mainSystem;
    }

    private Boolean checkBlankInput() {
        if (txtuname.getText().length() == 0 || txtpassword.getPassword().length == 0 || (chkbxHospAdmin.getText().length() == 0 && chkbxPatient.getText().length() == 0 && chkbxDoctor.getText().length() == 0 && chkbxCommAdmin.getText().length() == 0)) {
            return false;
        } else {
            return true;
        }
    }

    private boolean checkbox() {
        JCheckBox[] newList = new JCheckBox[4];
        newList[0] = chkbxCommAdmin;
        newList[1] = chkbxHospAdmin;
        newList[2] = chkbxDoctor;
        newList[3] = chkbxPatient;
        int k = 0;
        for (int i = 0; i < newList.length; i++) {
            if (newList[i].isSelected()) {
                k += 1;
            }
        }
        if (k == 1) {
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SplitPane = new javax.swing.JSplitPane();
        contorlPanel = new javax.swing.JPanel();
        contorlPanel1 = new javax.swing.JPanel();
        btnCity1 = new javax.swing.JButton();
        btnCitizen = new javax.swing.JButton();
        btnHospital = new javax.swing.JButton();
        btnDoctors = new javax.swing.JButton();
        Patients = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        Patients1 = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chkbxCommAdmin = new javax.swing.JCheckBox();
        chkbxHospAdmin = new javax.swing.JCheckBox();
        chkbxDoctor = new javax.swing.JCheckBox();
        chkbxPatient = new javax.swing.JCheckBox();
        brncreatecredentials = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        contorlPanel.setBackground(new java.awt.Color(238, 219, 240));

        contorlPanel1.setBackground(new java.awt.Color(238, 219, 240));
        contorlPanel1.setForeground(new java.awt.Color(204, 0, 51));

        btnCity1.setForeground(new java.awt.Color(0, 204, 204));
        btnCity1.setText("City");
        btnCity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCity1ActionPerformed(evt);
            }
        });

        btnCitizen.setForeground(new java.awt.Color(0, 204, 204));
        btnCitizen.setText("People");
        btnCitizen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitizenActionPerformed(evt);
            }
        });

        btnHospital.setForeground(new java.awt.Color(0, 204, 204));
        btnHospital.setText("Hospitals");
        btnHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalActionPerformed(evt);
            }
        });

        btnDoctors.setForeground(new java.awt.Color(0, 204, 204));
        btnDoctors.setText("Doctors");
        btnDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorsActionPerformed(evt);
            }
        });

        Patients.setForeground(new java.awt.Color(0, 204, 204));
        Patients.setText("Patients");
        Patients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientsActionPerformed(evt);
            }
        });

        btnlogout.setForeground(new java.awt.Color(0, 204, 204));
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        btnhome.setForeground(new java.awt.Color(0, 204, 204));
        btnhome.setText("Home");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        Patients1.setForeground(new java.awt.Color(0, 204, 204));
        Patients1.setText("View Doctors");
        Patients1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patients1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contorlPanel1Layout = new javax.swing.GroupLayout(contorlPanel1);
        contorlPanel1.setLayout(contorlPanel1Layout);
        contorlPanel1Layout.setHorizontalGroup(
            contorlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contorlPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contorlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlogout, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Patients1)
                    .addComponent(btnhome)
                    .addComponent(Patients)
                    .addComponent(btnCitizen)
                    .addComponent(btnHospital)
                    .addComponent(btnCity1)
                    .addComponent(btnDoctors))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        contorlPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Patients, Patients1, btnCitizen, btnCity1, btnDoctors, btnHospital, btnhome, btnlogout});

        contorlPanel1Layout.setVerticalGroup(
            contorlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contorlPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnhome)
                .addGap(18, 18, 18)
                .addComponent(btnCity1)
                .addGap(18, 18, 18)
                .addComponent(btnCitizen)
                .addGap(18, 18, 18)
                .addComponent(btnHospital)
                .addGap(18, 18, 18)
                .addComponent(btnDoctors)
                .addGap(18, 18, 18)
                .addComponent(Patients)
                .addGap(18, 18, 18)
                .addComponent(Patients1)
                .addGap(18, 18, 18)
                .addComponent(btnlogout)
                .addContainerGap(563, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contorlPanelLayout = new javax.swing.GroupLayout(contorlPanel);
        contorlPanel.setLayout(contorlPanelLayout);
        contorlPanelLayout.setHorizontalGroup(
            contorlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contorlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contorlPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contorlPanelLayout.setVerticalGroup(
            contorlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contorlPanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(contorlPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1031, Short.MAX_VALUE))
        );

        SplitPane.setLeftComponent(contorlPanel);

        workArea.setBackground(new java.awt.Color(246, 241, 255));
        workArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setText("Credential Creation");

        jLabel4.setText("Select role to create credentials");

        txtuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunameActionPerformed(evt);
            }
        });

        jLabel5.setText("Username");

        jLabel6.setText("Password");

        chkbxCommAdmin.setText("Community Admin");
        chkbxCommAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxCommAdminActionPerformed(evt);
            }
        });

        chkbxHospAdmin.setText("Hospital Admin");
        chkbxHospAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxHospAdminActionPerformed(evt);
            }
        });

        chkbxDoctor.setText("Doctor");
        chkbxDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxDoctorActionPerformed(evt);
            }
        });

        chkbxPatient.setText("Patient");
        chkbxPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxPatientActionPerformed(evt);
            }
        });

        brncreatecredentials.setBackground(new java.awt.Color(204, 204, 255));
        brncreatecredentials.setForeground(new java.awt.Color(255, 255, 255));
        brncreatecredentials.setText("Create Credentials");
        brncreatecredentials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brncreatecredentialsActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel7.setText("Set username and password");

        jLabel8.setFont(new java.awt.Font("PT Serif Caption", 1, 48)); // NOI18N
        jLabel8.setText("Admin Page");

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(chkbxCommAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkbxHospAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkbxDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(chkbxPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(workAreaLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(brncreatecredentials)
                            .addGroup(workAreaLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtuname, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(648, Short.MAX_VALUE))
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(chkbxCommAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkbxHospAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkbxDoctor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkbxPatient)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtuname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(brncreatecredentials)
                .addContainerGap(1554, Short.MAX_VALUE))
        );

        workAreaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtpassword, txtuname});

        SplitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SplitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCitizenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitizenActionPerformed
        // TODO add your handling code here:
        CreatePerson cjp1 = new CreatePerson(mainSystem, cred);
        SplitPane.setRightComponent(cjp1);

    }//GEN-LAST:event_btnCitizenActionPerformed

    private void btnCity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCity1ActionPerformed
        // TODO add your handling code here:
        CreateCityAdmin cjp = new CreateCityAdmin(mainSystem, cred);
        SplitPane.setRightComponent(cjp);
    }//GEN-LAST:event_btnCity1ActionPerformed

    private void btnHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalActionPerformed
        // TODO add your handling code here:
        CreateHospAdmin hjp = new CreateHospAdmin(mainSystem, cred);
        SplitPane.setRightComponent(hjp);
    }//GEN-LAST:event_btnHospitalActionPerformed

    private void btnDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorsActionPerformed
        // TODO add your handling code here:
        CreateDoctor djp = new CreateDoctor(mainSystem, cred);
        SplitPane.setRightComponent(djp);
    }//GEN-LAST:event_btnDoctorsActionPerformed

    private void PatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientsActionPerformed
        // TODO add your handling code here:
        DoctorPatientCreate dpjp = new DoctorPatientCreate(mainSystem, cred);
        SplitPane.setRightComponent(dpjp);
    }//GEN-LAST:event_PatientsActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        SystemAdmin frame = new SystemAdmin(mainSystem, cred);
        Window w = SwingUtilities.getWindowAncestor(SystemAdmin.this);
        w.setVisible(false);
        Main frame1 = new Main(mainSystem, cred);
        frame1.setVisible(true);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void chkbxCommAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxCommAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkbxCommAdminActionPerformed

    private void chkbxHospAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxHospAdminActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_chkbxHospAdminActionPerformed

    private void chkbxDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkbxDoctorActionPerformed

    private void chkbxPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxPatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkbxPatientActionPerformed

    private void brncreatecredentialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brncreatecredentialsActionPerformed
        // TODO add your handling code here:
        Credentials cred1 = cred.addNewCredentials();
        String uname = txtuname.getText();
        String pass = String.valueOf(txtpassword.getPassword());
        if (uname.equals("") || pass.equals("")) {
            JOptionPane.showMessageDialog(this, "Please fill the fields");
        } else if (checkbox()) {
            JOptionPane.showMessageDialog(this, "Please fill only a single role");

        } else {
            if (chkbxPatient.isSelected()) {
                String role = chkbxPatient.getText();
                chkbxPatient.setSelected(false);
                cred1.setPassword(pass);
                cred1.setRole(role);
                cred1.setUsername(uname);
            } else if (chkbxCommAdmin.isSelected()) {
                String role = chkbxCommAdmin.getText();
                chkbxCommAdmin.setSelected(false);
                cred1.setPassword(pass);
                cred1.setRole(role);
                cred1.setUsername(uname);
            } else if (chkbxDoctor.isSelected()) {
                String role = chkbxDoctor.getText();
                chkbxDoctor.setSelected(false);
                cred1.setPassword(pass);
                cred1.setRole(role);
                cred1.setUsername(uname);

            } else if (chkbxHospAdmin.isSelected()) {
                String role = chkbxHospAdmin.getText();
                chkbxHospAdmin.setSelected(false);
                cred1.setPassword(pass);
                cred1.setRole(role);
                cred1.setUsername(uname);

            } else {
                JOptionPane.showMessageDialog(this, "Please Input a Role");
                String role = "";
            }

            JOptionPane.showMessageDialog(this, "Credentials Created for user");
        }
    }//GEN-LAST:event_brncreatecredentialsActionPerformed

    private void txtunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtunameActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // TODO add your handling code here:
        SplitPane.setRightComponent(workArea);
    }//GEN-LAST:event_btnhomeActionPerformed

    private void Patients1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patients1ActionPerformed
        // TODO add your handling code here:

        CreatePatient pjp = new CreatePatient(mainSystem, cred);
        SplitPane.setRightComponent(pjp);

    }//GEN-LAST:event_Patients1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Patients;
    private javax.swing.JButton Patients1;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton brncreatecredentials;
    private javax.swing.JButton btnCitizen;
    private javax.swing.JButton btnCity1;
    private javax.swing.JButton btnDoctors;
    private javax.swing.JButton btnHospital;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnlogout;
    private javax.swing.JCheckBox chkbxCommAdmin;
    private javax.swing.JCheckBox chkbxDoctor;
    private javax.swing.JCheckBox chkbxHospAdmin;
    private javax.swing.JCheckBox chkbxPatient;
    private javax.swing.JPanel contorlPanel;
    private javax.swing.JPanel contorlPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtuname;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables

}
